## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('data-collection', ['core', 'simulator', 'mobility', 'wifi', 'olsr'])
    obj.source = ['main.cc', 'probe.cc', 'double-probe.cc', 'count-probe.cc', 'div-probe.cc', 'string-probe.cc', 'attribute-probe.cc', 'csv-collector.cc' ]
